export const SIGN_LABELS_EN: Record<string, string> = {
  abeille: 'bee', accessible: 'accessible', accident: 'accident', acheter: 'buy',
  adapte: 'adapted', adherer: 'join', adorer: 'love', aerer: 'air out',
  affreux: 'ugly', aide: 'help', ail: 'garlic', air: 'air',
  aller: 'go', allergique: 'allergic', allonge: 'lying down', allonger: 'stretch',
  amer: 'bitter', ami: 'friend', amour: 'love', analyser: 'analyze',
  angoisse: 'anxiety', animal: 'animal', annee: 'year', anniversaire: 'birthday',
  apercevoir: 'notice', apprendre: 'learn', apprendre_gaver: 'force-feed', apresmidi: 'afternoon',
  arbre: 'tree', arene: 'arena', argent: 'money', arreter: 'stop',
  asseoir: 'sit', association: 'association', attendre: 'wait', attraper: 'catch',
  augmenter: 'increase', aujourdhui: 'today', automne: 'autumn', autoroute: 'highway',
  avaler: 'swallow', avant: 'before', avion: 'airplane',
  baleine: 'whale', ballon: 'ball', banane: 'banana', bar: 'bar',
  barbe: 'beard', bateau: 'boat', beau: 'beautiful', bebe: 'baby',
  belier: 'ram', besoin: 'need', bete: 'animal', bibliotheque: 'library',
  bien: 'good', biensur: 'of course', bientot: 'soon', bilingue: 'bilingual',
  bizarre: 'strange', blanc: 'white', boire: 'drink', bombe: 'bomb',
  bonamanger: 'tasty', boulangerie: 'bakery', boxer: 'box',
  brosse: 'brush',
  cadeau: 'gift', cafe: 'coffee', cafesignes: 'deaf café', cahier: 'notebook',
  calculer: 'calculate', camera: 'camera', cancer: 'cancer', cannelle: 'cinnamon',
  carotte: 'carrot', casser: 'break', cave: 'cellar', celebre: 'famous',
  cerf: 'deer', cerne: 'dark circles', chagrine: 'sad', chambre: 'bedroom',
  champagne: 'champagne', changer: 'change', chanter: 'sing', chapeau: 'hat',
  chasser: 'hunt', chat: 'cat', chaud: 'hot', chauffage: 'heating',
  cheque: 'cheque', chercher: 'search', cheval: 'horse', cheveux: 'hair',
  chevre: 'goat', chien: 'dog', chocolat: 'chocolate', choisir: 'choose',
  choquer: 'shock', citoyen: 'citizen', clair: 'clear', classe: 'class',
  clef: 'key', club: 'club', cochon: 'pig', cocon: 'cocoon',
  coda: 'coda', college: 'middle school', comedien: 'actor', commander: 'order',
  comment: 'how', communiquer: 'communicate', compagnon: 'companion', comprendre: 'understand',
  concentrer: 'focus', conduire: 'drive', conference: 'conference', confiture: 'jam',
  congres: 'congress', connaitre: 'know', conseiller: 'advise', content: 'happy',
  corriger: 'correct', coudre: 'sew', couleur: 'color', couper: 'cut',
  couple: 'couple', courir: 'run', cours: 'lesson', court: 'short',
  cracher: 'spit', creatif: 'creative', creme: 'cream', crepes: 'crepes',
  creve: 'exhausted', crevette: 'shrimp', crier: 'shout', cuisine: 'kitchen',
  cuisiner: 'cook', cultiver: 'grow',
  d_accord: 'okay', dactylologie: 'fingerspelling', dangereux: 'dangerous', danser: 'dance',
  date: 'date', dauphin: 'dolphin', debat: 'debate', decoller: 'take off',
  decor: 'decor', delicieux: 'delicious', demander: 'ask', demiheure: 'half hour',
  deprime: 'depressed', desole: 'sorry', desordre: 'mess', dessin: 'drawing',
  detruire: 'destroy', devoirs: 'homework', diable: 'devil', dialogue: 'dialogue',
  diffuser: 'broadcast', dire: 'say', divorcer: 'divorce', docteur: 'doctor',
  donner: 'give', dormir: 'sleep', drapeau: 'flag', drole: 'funny',
  eau: 'water', echanger: 'exchange', ecole: 'school', ecouter: 'listen',
  ecraser: 'crush', ecrire: 'write', eglise: 'church', elephant: 'elephant',
  eleve: 'pupil', email: 'email', embouteillage: 'traffic jam', embrasser: 'kiss',
  enceinte: 'pregnant', enfant: 'child', enfin: 'finally', enseigner: 'teach',
  entendant: 'hearing', entreprise: 'company', entrer: 'enter', envie: 'desire',
  envoyer: 'send', epoque: 'era', equipe: 'team', erreur: 'error',
  escalade: 'climbing', escargot: 'snail', escrime: 'fencing', ete: 'summer',
  etourdir: 'dizzy', etranger: 'foreigner', etudiant: 'student', euros: 'euros',
  exprimer: 'express',
  fabriquer: 'make', fache: 'angry', faim: 'hungry', famille: 'family',
  fatigue: 'tired', fauteuil: 'armchair', feliciter: 'congratulate', femme: 'woman',
  fenetre: 'window', ferme: 'farm', festival: 'festival', feuilledarbre: 'leaf',
  fier: 'proud', fille: 'girl', film: 'film', fini: 'finished',
  flou: 'blurry', fonctionner: 'work', foot: 'football', foret: 'forest',
  fort: 'strong', four: 'oven', fraise: 'strawberry', framboise: 'raspberry',
  francais: 'french', froid: 'cold', fromage: 'cheese', fruit: 'fruit',
  frustre: 'frustrated',
  gants: 'gloves', garcon: 'boy', gargouiller: 'gurgle', gateau: 'cake',
  gel: 'gel', genereux: 'generous', glace: 'ice cream', global: 'global',
  golf: 'golf', gorge: 'throat', gorille: 'gorilla', gout: 'taste',
  graines: 'seeds', gratuit: 'free', grave: 'serious', grenouille: 'frog',
  grossir: 'gain weight', guerre: 'war',
  habits: 'clothes', handisport: 'parasport', helicoptere: 'helicopter', hier: 'yesterday',
  histoire: 'history', hiver: 'winter', homme: 'man', hopital: 'hospital',
  humain: 'human', humour: 'humor',
  idee: 'idea', ilyapas: 'there is none', imiter: 'imitate', important: 'important',
  index: 'index finger', infirmier: 'nurse', influencer: 'influence', informer: 'inform',
  inquiet: 'worried', interdit: 'forbidden', interessant: 'interesting', international: 'international',
  interprete: 'interpreter', inventer: 'invent', inviter: 'invite', ivre: 'drunk',
  jamais: 'never', jardin: 'garden', jeune: 'young', jeuxolympiques: 'olympic games',
  jouer: 'play', jour: 'day', journal: 'newspaper', journaliste: 'journalist',
  juste: 'fair',
  ketchup: 'ketchup',
  la: 'there', langue: 'language', laver: 'wash', lent: 'slow',
  lettre: 'letter', leverdujour: 'dawn', limonade: 'lemonade', lire: 'read',
  liste: 'list', lit: 'bed', livre: 'book', long: 'long',
  loup: 'wolf', lune: 'moon',
  magasin: 'store', magnifique: 'magnificent', mains: 'hands', maintenant: 'now',
  maison: 'house', mal: 'pain', malade: 'sick', maman: 'mom',
  manger: 'eat', manteau: 'coat', maquillage: 'makeup', marcher: 'walk',
  mariage: 'wedding', marie: 'married', marron: 'brown', match: 'match',
  matin: 'morning', menthe: 'mint', merci: 'thank you', metro: 'subway',
  miel: 'honey', mieux: 'better', mignon: 'cute', milliardaire: 'billionaire',
  mime: 'mime', miss: 'miss', mois: 'month', monde: 'world',
  montagne: 'mountain', moquer: 'mock', moto: 'motorcycle', mousse: 'foam',
  moutarde: 'mustard', mouton: 'sheep',
  naitre: 'be born', naviguer: 'navigate', neige: 'snow', nepasaimer: 'dislike',
  nerveux: 'nervous', noel: 'christmas', nom: 'name', normal: 'normal',
  note: 'note', nourriture: 'food', nouveau: 'new',
  odeur: 'smell', offrir: 'offer', oignon: 'onion', oncle: 'uncle',
  orange: 'orange', ordinateur: 'computer', ordonner: 'order', ou: 'where',
  ouragan: 'hurricane', ours: 'bear',
  pain: 'bread', papa: 'dad', papillon: 'butterfly', parachute: 'parachute',
  parc: 'park', parents: 'parents', parfait: 'perfect', parfumer: 'perfume',
  partir: 'leave', pas_vouloir: 'refuse', passion: 'passion', pasvouloir: 'refuse',
  pates: 'pasta', patinage: 'skating', pauvre: 'poor', payer: 'pay',
  pays: 'country', pedaler: 'pedal', penser: 'think', perdu: 'lost',
  personne: 'person', petit: 'small', petitdejeuner: 'breakfast', peur: 'fear',
  photo: 'photo', physique: 'physical', pied: 'foot', pieuvre: 'octopus',
  pingouin: 'penguin', pizza: 'pizza', pleurer: 'cry', plongee: 'diving',
  pluie: 'rain', plus: 'more', plusieurs: 'several', poisson: 'fish',
  poivre: 'pepper', pomme: 'apple', pompier: 'firefighter', portable: 'phone',
  porte: 'door', poule: 'chicken', pourquoi: 'why', pouvoir: 'can',
  pratique: 'practical', preparer: 'prepare', president: 'president', presse: 'press',
  preter: 'lend', prevenir: 'warn', prevoir: 'plan', prier: 'pray',
  prince: 'prince', princesse: 'princess', prochain: 'next', professeur: 'teacher',
  professionnel: 'professional', propre: 'clean', psychologue: 'psychologist',
  pub: 'pub', public: 'public', punir: 'punish',
  question: 'question', quoi: 'what',
  raisin: 'grape', randonner: 'hike', ranger: 'tidy', rassure: 'reassured',
  rater: 'fail', recevoir: 'receive', record: 'record', reflechir: 'think',
  regarder: 'watch', regulier: 'regular', reine: 'queen', rejoindre: 'join',
  rembourser: 'reimburse', remplacer: 'replace', remplir: 'fill', rencontre: 'meeting',
  rendezvous: 'appointment', reparer: 'repair', repetition: 'rehearsal', republique: 'republic',
  requin: 'shark', restaurant: 'restaurant', rester: 'stay', resultat: 'result',
  retour: 'return', reveiller: 'wake up', rever: 'dream', reviser: 'revise',
  riche: 'rich', roi: 'king', role: 'role', route: 'road',
  roux: 'red-haired', rue: 'street',
  salade: 'salad', sale: 'dirty', salledebain: 'bathroom', samedi: 'saturday',
  sandwich: 'sandwich', sang: 'blood', sante: 'health', sauce: 'sauce',
  saucisse: 'sausage', saucisson: 'salami', savoir: 'know', savon1main: 'soap',
  scorpion: 'scorpion', sebalader: 'stroll', sebrosserlesdents: 'brush teeth',
  sec: 'dry', sefaireavoir: 'be fooled', seffondrer: 'collapse', sel: 'salt',
  septembre: 'september', sereposer: 'rest', serviette: 'towel', siecle: 'century',
  signer: 'sign', singe: 'monkey', site: 'website', skateboard: 'skateboard',
  skier: 'ski', soigner: 'care for', soir: 'evening', soleil: 'sun',
  souffrant: 'suffering', sourd: 'deaf', souris: 'mouse', soustitres: 'subtitles',
  souvent: 'often', sport: 'sport', style: 'style', stylo: 'pen',
  sucre: 'sugar', super: 'great', surprise: 'surprise', sushi: 'sushi',
  sympa: 'nice',
  table: 'table', tableau: 'board', tache: 'task', tapis: 'carpet',
  taquiner: 'tease', tasse: 'cup', tatouage: 'tattoo', taureau: 'bull',
  taxi: 'taxi', telephoner: 'call', television: 'television', temoin: 'witness',
  temperature: 'temperature', the: 'tea', theatre: 'theater', tigre: 'tiger',
  toilettes: 'toilet', tomber: 'fall', tortue: 'turtle', tour_batiment: 'skyscraper',
  tradition: 'tradition', train: 'train', tranquille: 'calm', transformer: 'transform',
  travailler: 'work', trimestre: 'term', triste: 'sad',
  uf: 'egg', universite: 'university',
  vache: 'cow', velo: 'bicycle', vendre: 'sell', venir: 'come',
  ver: 'worm', verglas: 'black ice', verre: 'glass', vert: 'green',
  vexe: 'upset', vide: 'empty', vie: 'life', vieux: 'old',
  ville: 'city', visio: 'video call', visiter: 'visit', vite: 'fast',
  voir: 'see', voiture: 'car', voler: 'steal', voler_ailes: 'fly',
  volleyball: 'volleyball', vomir: 'vomit', vouloir: 'want', vouloir_objectif: 'goal',
  vraiment: 'really',
};

export const SIGN_LABELS_TR: Record<string, string> = {
  abeille: 'arı', accessible: 'erişilebilir', accident: 'kaza', acheter: 'satın almak',
  adapte: 'uyarlanmış', adherer: 'katılmak', adorer: 'sevmek', aerer: 'havalandırmak',
  affreux: 'korkunç', aide: 'yardım', ail: 'sarımsak', air: 'hava',
  aller: 'gitmek', allergique: 'alerjik', allonge: 'uzanmış', allonger: 'uzatmak',
  amer: 'acı', ami: 'arkadaş', amour: 'aşk', analyser: 'analiz etmek',
  angoisse: 'kaygı', animal: 'hayvan', annee: 'sene', anniversaire: 'doğum günü',
  apercevoir: 'fark etmek', apprendre: 'öğrenmek', apprendre_gaver: 'zorla beslemek', apresmidi: 'öğleden sonra',
  arbre: 'ağaç', arene: 'arena', argent: 'para', arreter: 'durmak',
  asseoir: 'oturmak', association: 'dernek', attendre: 'beklemek', attraper: 'yakalamak',
  augmenter: 'artırmak', aujourdhui: 'bugün', automne: 'sonbahar', autoroute: 'otoyol',
  avaler: 'yutmak', avant: 'önce', avion: 'uçak',
  baleine: 'balina', ballon: 'balon', banane: 'muz', bar: 'bar',
  barbe: 'sakal', bateau: 'tekne', beau: 'güzel', bebe: 'bebek',
  belier: 'koç', besoin: 'ihtiyaç', bete: 'hayvan', bibliotheque: 'kütüphane',
  bien: 'iyi', biensur: 'tabii ki', bientot: 'yakında', bilingue: 'iki dilli',
  bizarre: 'tuhaf', blanc: 'beyaz', boire: 'içmek', bombe: 'bomba',
  bonamanger: 'lezzetli', boulangerie: 'fırın', boxer: 'boks yapmak',
  brosse: 'fırça',
  cadeau: 'hediye', cafe: 'kahve', cafesignes: 'sağır kafe', cahier: 'defter',
  calculer: 'hesaplamak', camera: 'kamera', cancer: 'kanser', cannelle: 'tarçın',
  carotte: 'havuç', casser: 'kırmak', cave: 'bodrum', celebre: 'ünlü',
  cerf: 'geyik', cerne: 'göz altı halkası', chagrine: 'üzgün', chambre: 'oda',
  champagne: 'şampanya', changer: 'değiştirmek', chanter: 'şarkı söylemek', chapeau: 'şapka',
  chasser: 'avlamak', chat: 'kedi', chaud: 'sıcak', chauffage: 'ısıtma',
  cheque: 'çek', chercher: 'aramak', cheval: 'at', cheveux: 'saç',
  chevre: 'keçi', chien: 'köpek', chocolat: 'çikolata', choisir: 'seçmek',
  choquer: 'şok etmek', citoyen: 'vatandaş', clair: 'açık', classe: 'sınıf',
  clef: 'anahtar', club: 'kulüp', cochon: 'domuz', cocon: 'koza',
  coda: 'coda', college: 'ortaokul', comedien: 'aktör', commander: 'sipariş vermek',
  comment: 'nasıl', communiquer: 'iletişim kurmak', compagnon: 'arkadaş', comprendre: 'anlamak',
  concentrer: 'odaklanmak', conduire: 'sürmek', conference: 'konferans', confiture: 'reçel',
  congres: 'kongre', connaitre: 'tanımak', conseiller: 'tavsiye etmek', content: 'mutlu',
  corriger: 'düzeltmek', coudre: 'dikmek', couleur: 'renk', couper: 'kesmek',
  couple: 'çift', courir: 'koşmak', cours: 'ders', court: 'kısa',
  cracher: 'tükürmek', creatif: 'yaratıcı', creme: 'krema', crepes: 'krep',
  creve: 'bitkin', crevette: 'karides', crier: 'bağırmak', cuisine: 'mutfak',
  cuisiner: 'pişirmek', cultiver: 'yetiştirmek',
  d_accord: 'tamam', dactylologie: 'parmak alfabesi', dangereux: 'tehlikeli', danser: 'dans etmek',
  date: 'tarih', dauphin: 'yunus', debat: 'tartışma', decoller: 'kalkmak',
  decor: 'dekor', delicieux: 'lezzetli', demander: 'sormak', demiheure: 'yarım saat',
  deprime: 'depresif', desole: 'özür dilerim', desordre: 'dağınıklık', dessin: 'çizim',
  detruire: 'yıkmak', devoirs: 'ödev', diable: 'şeytan', dialogue: 'diyalog',
  diffuser: 'yayınlamak', dire: 'söylemek', divorcer: 'boşanmak', docteur: 'doktor',
  donner: 'vermek', dormir: 'uyumak', drapeau: 'bayrak', drole: 'komik',
  eau: 'su', echanger: 'değiş tokuş', ecole: 'okul', ecouter: 'dinlemek',
  ecraser: 'ezmek', ecrire: 'yazmak', eglise: 'kilise', elephant: 'fil',
  eleve: 'öğrenci', email: 'e-posta', embouteillage: 'trafik sıkışıklığı', embrasser: 'öpmek',
  enceinte: 'hamile', enfant: 'çocuk', enfin: 'sonunda', enseigner: 'öğretmek',
  entendant: 'duyan', entreprise: 'şirket', entrer: 'girmek', envie: 'istek',
  envoyer: 'göndermek', epoque: 'dönem', equipe: 'takım', erreur: 'hata',
  escalade: 'tırmanma', escargot: 'salyangoz', escrime: 'eskrim', ete: 'yaz',
  etourdir: 'başını döndürmek', etranger: 'yabancı', etudiant: 'öğrenci', euros: 'euro',
  exprimer: 'ifade etmek',
  fabriquer: 'yapmak', fache: 'sinirli', faim: 'aç', famille: 'aile',
  fatigue: 'yorgun', fauteuil: 'koltuk', feliciter: 'tebrik etmek', femme: 'kadın',
  fenetre: 'pencere', ferme: 'çiftlik', festival: 'festival', feuilledarbre: 'yaprak',
  fier: 'gururlu', fille: 'kız', film: 'film', fini: 'bitti',
  flou: 'bulanık', fonctionner: 'çalışmak', foot: 'futbol', foret: 'orman',
  fort: 'güçlü', four: 'fırın', fraise: 'çilek', framboise: 'ahududu',
  francais: 'fransızca', froid: 'soğuk', fromage: 'peynir', fruit: 'meyve',
  frustre: 'hayal kırıklığı',
  gants: 'eldiven', garcon: 'oğlan', gargouiller: 'guruldamak', gateau: 'pasta',
  gel: 'jel', genereux: 'cömert', glace: 'dondurma', global: 'küresel',
  golf: 'golf', gorge: 'boğaz', gorille: 'goril', gout: 'tat',
  graines: 'tohumlar', gratuit: 'ücretsiz', grave: 'ciddi', grenouille: 'kurbağa',
  grossir: 'kilo almak', guerre: 'savaş',
  habits: 'kıyafetler', handisport: 'engelli sporu', helicoptere: 'helikopter', hier: 'dün',
  histoire: 'tarih', hiver: 'kış', homme: 'adam', hopital: 'hastane',
  humain: 'insan', humour: 'mizah',
  idee: 'fikir', ilyapas: 'yok', imiter: 'taklit etmek', important: 'önemli',
  index: 'işaret parmağı', infirmier: 'hemşire', influencer: 'etkilemek', informer: 'bilgilendirmek',
  inquiet: 'endişeli', interdit: 'yasak', interessant: 'ilginç', international: 'uluslararası',
  interprete: 'tercüman', inventer: 'icat etmek', inviter: 'davet etmek', ivre: 'sarhoş',
  jamais: 'asla', jardin: 'bahçe', jeune: 'genç', jeuxolympiques: 'olimpiyat oyunları',
  jouer: 'oynamak', jour: 'gün', journal: 'gazete', journaliste: 'gazeteci',
  juste: 'adil',
  ketchup: 'ketçap',
  la: 'orada', langue: 'dil', laver: 'yıkamak', lent: 'yavaş',
  lettre: 'mektup', leverdujour: 'şafak', limonade: 'limonata', lire: 'okumak',
  liste: 'liste', lit: 'yatak', livre: 'kitap', long: 'uzun',
  loup: 'kurt', lune: 'dolunay',
  magasin: 'market', magnifique: 'muhteşem', mains: 'eller', maintenant: 'şimdi',
  maison: 'ev', mal: 'acı', malade: 'hasta', maman: 'anne',
  manger: 'yemek', manteau: 'palto', maquillage: 'makyaj', marcher: 'yürümek',
  mariage: 'düğün', marie: 'evli', marron: 'kahverengi', match: 'maç',
  matin: 'sabah', menthe: 'nane', merci: 'teşekkürler', metro: 'metro',
  miel: 'bal', mieux: 'daha iyi', mignon: 'sevimli', milliardaire: 'milyarder',
  mime: 'pandomim', miss: 'bayan', mois: 'ay', monde: 'dünya',
  montagne: 'dağ', moquer: 'alay etmek', moto: 'motosiklet', mousse: 'köpük',
  moutarde: 'hardal', mouton: 'koyun',
  naitre: 'doğmak', naviguer: 'gezinmek', neige: 'kar', nepasaimer: 'sevmemek',
  nerveux: 'gergin', noel: 'noel', nom: 'isim', normal: 'normal',
  note: 'not', nourriture: 'yiyecek', nouveau: 'yeni',
  odeur: 'koku', offrir: 'sunmak', oignon: 'soğan', oncle: 'amca',
  orange: 'portakal', ordinateur: 'bilgisayar', ordonner: 'emretmek', ou: 'nerede',
  ouragan: 'kasırga', ours: 'ayı',
  pain: 'ekmek', papa: 'baba', papillon: 'kelebek', parachute: 'paraşüt',
  parc: 'park', parents: 'ebeveynler', parfait: 'mükemmel', parfumer: 'parfüm sürmek',
  partir: 'ayrılmak', pas_vouloir: 'reddetmek', passion: 'tutku', pasvouloir: 'reddetmek',
  pates: 'makarna', patinage: 'paten', pauvre: 'fakir', payer: 'ödemek',
  pays: 'ülke', pedaler: 'pedal çevirmek', penser: 'düşünmek', perdu: 'kaybolmuş',
  personne: 'kişi', petit: 'küçük', petitdejeuner: 'kahvaltı', peur: 'korku',
  photo: 'fotoğraf', physique: 'fiziksel', pied: 'ayak', pieuvre: 'ahtapot',
  pingouin: 'penguen', pizza: 'pizza', pleurer: 'ağlamak', plongee: 'dalış',
  pluie: 'yağmur', plus: 'daha fazla', plusieurs: 'birkaç', poisson: 'balık',
  poivre: 'biber', pomme: 'elma', pompier: 'itfaiyeci', portable: 'cep telefonu',
  porte: 'kapı', poule: 'tavuk', pourquoi: 'neden', pouvoir: 'yapabilmek',
  pratique: 'pratik', preparer: 'hazırlamak', president: 'cumhurbaşkanı', presse: 'basın',
  preter: 'ödünç vermek', prevenir: 'uyarmak', prevoir: 'planlamak', prier: 'dua etmek',
  prince: 'prens', princesse: 'prenses', prochain: 'sonraki', professeur: 'öğretmen',
  professionnel: 'profesyonel', propre: 'temiz', psychologue: 'psikolog',
  pub: 'pub', public: 'kamuoyu', punir: 'cezalandırmak',
  question: 'soru', quoi: 'ne',
  raisin: 'üzüm', randonner: 'yürüyüş yapmak', ranger: 'düzenlemek', rassure: 'rahatlamış',
  rater: 'başarısız olmak', recevoir: 'almak', record: 'rekor', reflechir: 'düşünmek',
  regarder: 'izlemek', regulier: 'düzenli', reine: 'kraliçe', rejoindre: 'katılmak',
  rembourser: 'geri ödemek', remplacer: 'değiştirmek', remplir: 'doldurmak', rencontre: 'buluşma',
  rendezvous: 'randevu', reparer: 'tamir etmek', repetition: 'prova', republique: 'cumhuriyet',
  requin: 'köpekbalığı', restaurant: 'restoran', rester: 'kalmak', resultat: 'sonuç',
  retour: 'dönüş', reveiller: 'uyandırmak', rever: 'rüya görmek', reviser: 'gözden geçirmek',
  riche: 'zengin', roi: 'kral', role: 'rol', route: 'yol',
  roux: 'kızıl saçlı', rue: 'sokak',
  salade: 'salata', sale: 'kirli', salledebain: 'banyo', samedi: 'cumartesi',
  sandwich: 'sandviç', sang: 'kan', sante: 'sağlık', sauce: 'sos',
  saucisse: 'sosis', saucisson: 'sucuk', savoir: 'bilmek', savon1main: 'sabun',
  scorpion: 'akrep', sebalader: 'gezinmek', sebrosserlesdents: 'diş fırçalamak',
  sec: 'kuru', sefaireavoir: 'kandırılmak', seffondrer: 'çökmek', sel: 'tuz',
  septembre: 'eylül', sereposer: 'dinlenmek', serviette: 'havlu', siecle: 'yüzyıl',
  signer: 'işaret etmek', singe: 'maymun', site: 'web sitesi', skateboard: 'kaykay',
  skier: 'kayak yapmak', soigner: 'bakmak', soir: 'akşam', soleil: 'güneş',
  souffrant: 'acı çeken', sourd: 'sağır', souris: 'fare', soustitres: 'altyazı',
  souvent: 'sık sık', sport: 'spor', style: 'stil', stylo: 'kalem',
  sucre: 'şeker', super: 'harika', surprise: 'sürpriz', sushi: 'suşi',
  sympa: 'sempatik',
  table: 'masa', tableau: 'tahta', tache: 'görev', tapis: 'halı',
  taquiner: 'takılmak', tasse: 'fincan', tatouage: 'dövme', taureau: 'boğa',
  taxi: 'taksi', telephoner: 'aramak', television: 'televizyon', temoin: 'tanık',
  temperature: 'sıcaklık', the: 'çay', theatre: 'tiyatro', tigre: 'kaplan',
  toilettes: 'tuvalet', tomber: 'düşmek', tortue: 'kaplumbağa', tour_batiment: 'gökdelen',
  tradition: 'gelenek', train: 'tren', tranquille: 'sakin', transformer: 'dönüştürmek',
  travailler: 'çalışmak', trimestre: 'dönem', triste: 'üzgün',
  uf: 'yumurta', universite: 'üniversite',
  vache: 'inek', velo: 'bisiklet', vendre: 'satmak', venir: 'gelmek',
  ver: 'solucan', verglas: 'buz', verre: 'bardak', vert: 'yeşil',
  vexe: 'gücenmiş', vide: 'boş', vie: 'hayat', vieux: 'yaşlı',
  ville: 'şehir', visio: 'video görüşme', visiter: 'ziyaret etmek', vite: 'hızlı',
  voir: 'görmek', voiture: 'araba', voler: 'çalmak', voler_ailes: 'uçmak',
  volleyball: 'voleybol', vomir: 'kusmak', vouloir: 'istemek', vouloir_objectif: 'hedef',
  vraiment: 'gerçekten',
};

export function getSignLabel(frenchWord: string, language: string): string {
  if (language === 'en') return SIGN_LABELS_EN[frenchWord] ?? frenchWord;
  if (language === 'tr') return SIGN_LABELS_TR[frenchWord] ?? frenchWord;
  return frenchWord;
}
